/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.21
 * Generated at: 2019-10-13 01:50:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/library/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/2ndProjectBook/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1562030373597L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<title>별마당도서관에 방문하신 것을 환영합니다!</title>\n");
      out.write("\t<style>\n");
      out.write("table, th, td {\n");
      out.write("\tborder: 1px solid #bcbcbc;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("table {\n");
      out.write("\twidth: 100%;\n");
      out.write("\theight: 200px;\n");
      out.write("\ttext-align: center;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#searchBox, #leftRightArea {\n");
      out.write("\twidth: 25%;\n");
      out.write("\tmargin: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input, button {\n");
      out.write("\tborder: 1px solid black;\n");
      out.write("\tbackground-color: rgba(0, 0, 0, 0);\n");
      out.write("\tcolor: black;\n");
      out.write("\tpadding: 5px;\n");
      out.write("\tfont-size: 18px;\n");
      out.write("}\n");
      out.write("\n");
      out.write("input:hover {\n");
      out.write("\tcolor: black;\n");
      out.write("\tbackground-color: #D8D8D8;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n");
      out.write("<script>\n");
      out.write("var booknum = \"\";\n");
      out.write("var startNum = 0;\n");
      out.write("var sLength = 5;\n");
      out.write("var numberTh;\n");
      out.write("$(function(){\n");
      out.write("\t\n");
      out.write("\t$(\"#printbtn\").click(function(){\n");
      out.write("\t\twindow.location=\"/libs/\";\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#bookDetailBtn\",function(){\n");
      out.write("\t\tbooknum = $(this).attr(\"booknum\");\n");
      out.write("\t\tboardDetail();\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(\"#selectPaging\").change(function(){\n");
      out.write("\t\tvar selectPaging = $(\"#selectPaging\").val();\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"selectPaging\",\n");
      out.write("\t\t\tdata:{\n");
      out.write("\t\t\t\tselectPaging:selectPaging\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess:function(serverData){\n");
      out.write("\t\t\t\tif(serverData==\"yes\"){\n");
      out.write("\t\t\t\t\twindow.location=\"/libs/selectBook\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#toLeftBtn\",function(){\n");
      out.write("\t\tnumberTh-=5;\n");
      out.write("\t\tprintBorrowList(numberTh);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#toRightBtn\",function(){\n");
      out.write("\t\tnumberTh+=5;\n");
      out.write("\t\tprintBorrowList(numberTh);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#borrowList\",function(){\n");
      out.write("\t\tnumberTh=4;\n");
      out.write("\t\tprintBorrowList(numberTh);\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t$(\".top\").click(function(){\n");
      out.write("\t\treturn $(\"html, body\").animate({scrollTop:0},300),!1})});\n");
      out.write("\n");
      out.write("\n");
      out.write("\tfunction printBorrowList(numberTh){\n");
      out.write("\t\t$(\"#printArea\").html(\"\");\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"selectLend\",\n");
      out.write("\t\t\tdata:{\n");
      out.write("\t\t\t\tnumberTh:numberTh\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\tsuccess:function(serverData){\n");
      out.write("\t\t\t\tif(serverData.length==0){\n");
      out.write("\t\t\t\t\talert(\"출력할 대출 이력이 존재하지 않습니다\");\n");
      out.write("\t\t\t\t\twindow.location=\"/libs/\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tvar str=\"\";\n");
      out.write("\t\t\t\tvar status = \"\";\n");
      out.write("\t\t\t\tvar startdate = \"\";\n");
      out.write("\t\t\t\tvar endReturnDate = \"\";\n");
      out.write("\t\t\t\tvar delay=\"\";\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\tstr+=\"<br>\";\n");
      out.write("\t\t\t\tstr+=\"<div id = 'leftRightArea'>\";\n");
      out.write("\t\t\t\tstr+=\"<input id = 'toLeftBtn' type = 'button' value = '&lt;' style='width:100pt;height:25pt;'>\";\n");
      out.write("\t\t\t\tstr+=\"<input id = 'toRightBtn' type = 'button' value = '&gt;' style='width:100pt;height:25pt;'>\";\n");
      out.write("\t\t\t\tstr+=\"</div>\";\n");
      out.write("\t\t\t\tstr+=\"<br>\";\n");
      out.write("\t\t\t\tstr+=\"<table>\";\n");
      out.write("\t\t\t\tstr+=\"<tr>\";\n");
      out.write("\t\t\t\tstr+=\"<th>대출일</th>\";\n");
      out.write("\t\t\t\tstr+=\"<th>반납일</th>\";\n");
      out.write("\t\t\t\tstr+=\"<th>이미지</th>\";\n");
      out.write("\t\t\t\tstr+=\"<th>제목</th>\";\n");
      out.write("\t\t\t\tstr+=\"<th>상태</th>\";\n");
      out.write("\t\t\t\tstr+=\"</tr>\";\n");
      out.write("\t\t\t\tfor(var i = 0 ; i < serverData.length ; i++){\n");
      out.write("\t\n");
      out.write("\t\t\t\t\tstatus = serverData[i].status;\n");
      out.write("\t\t\t\t\tstartdate = serverData[i].startdate;\n");
      out.write("\t\t\t\t\tdelay = serverData[i].delay;\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\tswitch(status){\n");
      out.write("\t\t\t\t\tcase \"reserved\":\n");
      out.write("\t\t\t\t\t\tstatus=\"대출신청중\";\n");
      out.write("\t\t\t\t\t\tstartdate=\"\";\n");
      out.write("\t\t\t\t\t\tendReturnDate=\"\";\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\tcase \"lent\":\n");
      out.write("\t\t\t\t\t\tstatus=\"대출 중\";\n");
      out.write("\t\t\t\t\t\tif(delay>-4){\n");
      out.write("\t\t\t\t\t\t\tstatus+=\"<br><input id = 'pleaseReturnBtn' delay = '\"+delay+\"' type='button' value = '반납임박'>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\tendReturnDate=serverData[i].enddate;\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\tcase \"returned\":\n");
      out.write("\t\t\t\t\t\tstatus=\"반납 완료\";\n");
      out.write("\t\t\t\t\t\tendReturnDate=serverData[i].returndate;\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\tcase \"rejected\":\n");
      out.write("\t\t\t\t\t\tstatus=\"대출 거절\";\n");
      out.write("\t\t\t\t\t\tstartdate=\"\";\n");
      out.write("\t\t\t\t\t\tendReturnDate=\"\";\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\tcase \"delayed\":\n");
      out.write("\t\t\t\t\t\tstatus=\"<font color=red>연체</font>\";\n");
      out.write("\t\t\t\t\t\tendReturnDate=serverData[i].enddate;\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\tcase \"delay_returned\":\n");
      out.write("\t\t\t\t\t\tstatus=\"연체되어 반납 됨\";\n");
      out.write("\t\t\t\t\t\tendReturnDate=serverData[i].returndate;\n");
      out.write("\t\t\t\t\t\tbreak;\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\tstr+=\"<tr>\";\n");
      out.write("\t\t\t\tstr+=\"<td><h2>\"+startdate+\"</h2></td>\";\n");
      out.write("\t\t\t\tstr+=\"<td><h2>\"+endReturnDate+\"</h2></td>\";\n");
      out.write("\t\t\t\tstr+=\"<td><img src='resources/saveimg/\"+serverData[i].imageurl+\"' width='150' height='150'></td>\";\n");
      out.write("\t\t\t\tstr+=\"<td><h2>\"+serverData[i].title+\"</h2></td>\";\n");
      out.write("\t\t\t\tstr+=\"<td><h2>\"+status+\"</h2></td>\";\n");
      out.write("\t\t\t\tstr+=\"</tr>\";\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tstr+=\"</table>\";\n");
      out.write("\t\t\t\t$(\"#printArea\").html(\"\");\n");
      out.write("\t\t\t\t$(\"#printArea\").append(str);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t$(\"#moveSignup\").click(function(){\n");
      out.write("\t\twindow.location=\"/libs/moveSignup\";\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#pleaseReturnBtn\",function(){\n");
      out.write("\t\talert(\"반납일까지 \"+$(this).attr(\"delay\")+\" 일 남았습니다\");\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t$(document).on(\"click\",\"#borrowbtn\",function(){\n");
      out.write("\t\tbooknum = $(this).attr(\"booknum\");\n");
      out.write("\t\ttitle = $(this).attr(\"title\");\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl:\"insertLend\",\n");
      out.write("\t\t\tdata:{\n");
      out.write("\t\t\t\tbooknum:booknum,\n");
      out.write("\t\t\t\ttitle:title\n");
      out.write("\t\t\t},\n");
      out.write("\t\t\ttype:\"POST\",\n");
      out.write("\t\t\tsuccess:function(serverData){\n");
      out.write("\t\t\t\tif(serverData==\"no\"){\n");
      out.write("\t\t\t\t\talert(\"대출 신청에 실패하였습니다\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t\talert(\"대출 신청이 완료되었습니다\");\n");
      out.write("\t\t\t\t\t$(\"#borrowbtnArea\").html(\"★ 신청 완료 ★\");\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write(" function boardDetail(){\n");
      out.write("\t $.ajax({\n");
      out.write("\t\t \n");
      out.write("\t\t url:\"selectOneBook\",\n");
      out.write("\t\t data:{\n");
      out.write("\t\t\t booknum:booknum\n");
      out.write("\t\t },\n");
      out.write("\t\t success:function(serverData){\n");
      out.write("\t\n");
      out.write("\t\t \t var str = \"\";\n");
      out.write("\t\t \t str+=\"<br><br><br>\";\n");
      out.write("\t\t\t str+=\"<table>\";\n");
      out.write("\t\t\t str+=\"<tr>\";\n");
      out.write("\t\t\t str+=\"<td colspan='2'>\";\n");
      out.write("\t\t\t str+=\"<img src='resources/saveimg/\"+serverData.imageurl+\"' width='400' height='400'>\";\n");
      out.write("\t\t\t str+=\"</td>\";\n");
      out.write("\t\t\t str+=\"<td>\";\n");
      out.write("\t\t\t str+=\"</td>\";\n");
      out.write("\t\t\t str+=\"</tr>\";\n");
      out.write("\t\t\t str+=\"<tr>\";\n");
      out.write("\t\t\t str+=\"<th><h1>제목</h1></th>\";\n");
      out.write("\t\t\t str+=\"<th><h1>\"+serverData.title+\"</h1></th>\";\n");
      out.write("\t\t\t str+=\"</tr>\";\n");
      out.write("\t\t\t str+=\"<tr>\";\n");
      out.write("\t\t\t str+=\"<th><h1>출판사</h1></th>\";\n");
      out.write("\t\t\t str+=\"<th><h1>\"+serverData.publisher+\"</h1></th>\";\n");
      out.write("\t\t\t str+=\"\t</tr>\";\n");
      out.write("\t\t\t str+=\"<tr>\";\n");
      out.write("\t\t\t str+=\"<th><h1>저자</h1></th>\";\n");
      out.write("\t\t\t str+=\"<th><h1>\"+serverData.author+\"</h1></th>\";\n");
      out.write("\t\t\t str+=\"</tr>\";\n");
      out.write("\t\t\t str+=\"<tr>\";\n");
      out.write("\t\t\t str+=\"<th><h1>대출가능</h1></th>\";\n");
      out.write("\t\t\t str+=\"<th><h1>\"+serverData.status+\"</h1>\";\n");
      out.write("\t\t\t str+=\"");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\t\t\t str+=\"<br></th>\";\n");
      out.write("\t\t\t str+=\"</tr>\";\n");
      out.write("\t\t\t str+=\"<tr>\"; \n");
      out.write("\t\t\t str+=\"<th><h1>내용</h1></th>\";\n");
      out.write("\t\t\t str+=\"<th><h1>\"+serverData.content+\"</h1></th>\";\n");
      out.write("\t\t\t str+=\"</tr>\";\n");
      out.write("\t\t\t str+=\"</table>\";\n");
      out.write("\t\t\t$(\"#printArea\").html(\"\");\n");
      out.write("\t\t\t$(\"#printArea\").append(str);\n");
      out.write("\t\t\t \n");
      out.write("\t\t }\n");
      out.write("\t });\n");
      out.write(" }\n");
      out.write("\t\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("<h1>\n");
      out.write("별마당 도서관\n");
      out.write("</h1>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<th>\n");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</th>\n");
      out.write("<th><input id = \"printbtn\" type=button style=\"width:300pt;height:45pt;\" value=\"도서목록\">\n");
      out.write("</th>\n");
      out.write("<th>\n");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</th>\n");
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("<div id = \"printArea\">\n");
      out.write("<h2>\n");
      out.write("<a href=\"selectBook?page=1&searchWord=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchTopic=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">&lt;&lt;</a>\n");
      out.write("<a href=\"selectBook?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.startPageGroup-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchWord=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchTopic=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">&lt;</a>\n");
      out.write("\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<a href=\"selectBook?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.endPageGroup+1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchWord=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchTopic=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">&gt;</a>\n");
      out.write("<a href=\"selectBook?page=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.totalRecordsCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchWord=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("&searchTopic=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">&gt;&gt;</a>\n");
      out.write("\n");
      out.write("<select id = \"selectPaging\" style=\"width:200px; height:40px;\">\n");
      out.write("<option value = \"선택\">선택</option>\n");
      out.write("<option value = \"5\">5</option>\n");
      out.write("<option value = \"10\">10</option>\n");
      out.write("<option value = \"20\">20</option>\n");
      out.write("</select>\n");
      out.write("개씩 표시\n");
      out.write("</h2>\n");
      out.write("\n");
      out.write("<div id = \"searchBox\">\n");
      out.write("<form action = \"selectBook\" method = \"get\">\n");
      out.write("<select name = \"searchTopic\" style=\"width:200px; height:40px;\">\n");
      out.write("<option value = '제목'>제목</option>\n");
      out.write("<option value = '출판사'>출판사</option>\n");
      out.write("<option value = '저자'>저자</option>\n");
      out.write("<option value = '대출가능'>대출가능</option>\n");
      out.write("</select>\n");
      out.write("<input type ='text' name = \"searchWord\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" style=\"width:200px; height:40px;\">\n");
      out.write("<input type = \"hidden\" value = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.currentPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("<input type = 'submit' value = '검색' style=\"width:100px; height:40px;\">\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("\t\t\t\t\n");
      out.write("<table>\n");
      out.write("<tr>\n");
      out.write("<th>이미지</th>\n");
      out.write("<th>제목</th>\n");
      out.write("<th>출판사</th>\n");
      out.write("<th>저자</th>\n");
      out.write("<th>대출가능</th>\n");
      out.write("</tr>\n");
      out.write("\n");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("<br>\n");
      out.write("<button type='button' class = 'top'>맨 위로 ↑</button>\n");
      out.write("<br>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(246,10) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\";\n");
          out.write("\t\t\n");
          out.write("\t\t\t \n");
          out.write("\t\t\t if(serverData.status=='Y'){\n");
          out.write("\t\t\t\n");
          out.write("\t\t\t\t str+=\"<div id = 'borrowbtnArea'>\";\n");
          out.write("\t\t\t\t str+=\"<input id = 'borrowbtn' title = '\"+serverData.title+\"' booknum = '\"+serverData.booknum+\"' type = 'button' value = '대출신청'>\";\n");
          out.write("\t\t\t\t str+=\"</div>\";\n");
          out.write("\t\t\t\t \n");
          out.write("\t\t\t }\n");
          out.write("\t\t\t \n");
          out.write("\t\t\t str+=\" ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(284,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty sessionScope.loginId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("<form action = \"login\" method = \"POST\">\n");
          out.write("<input id = \"userid\" type = \"text\" name = \"userid\"><br>\n");
          out.write("<input id = \"password\" type = \"password\" name = \"password\"><br>\n");
          out.write("<input id = \"moveSignup\" type = \"button\" value = \"회원가입\">\n");
          out.write("<input id = \"loginbtn\" type = \"submit\" value = \"로그인\">\n");
          out.write("</form>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(292,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<br>\n");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님, 로그인 하셨습니다.<br><br>\n");
          out.write(" <img src=\"resources/saveimg/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" width=\"150\" height=\"150\">\n");
          out.write("<br>\n");
          out.write("회원번호<br>\n");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<br><br>\n");
          out.write("<input id = \"moveSignup\" type = \"button\" value = \"회원정보수정\">\n");
          out.write("<form action = \"logout\" method = \"GET\">\n");
          out.write("<input id = \"logoutbtn\" type =\"submit\" value = \"로그아웃\">\n");
          out.write("</form>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/home.jsp(307,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!empty sessionScope.loginId }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("<input id = \"borrowList\" type=button style=\"width:300pt;height:45pt;\" value=\"대출이력\">\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(319,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("counter");
      // /WEB-INF/views/home.jsp(319,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.startPageGroup}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/home.jsp(319,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${navi.endPageGroup}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("<a href=\"selectBook?page=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${counter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&searchWord=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchWord}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&searchTopic=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${searchTopic}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${counter }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("&nbsp;</a>\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(358,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/home.jsp(358,0) '${bList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${bList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/home.jsp(358,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("book");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\n");
            out.write("<tr>\n");
            out.write("<td>\n");
            out.write("<img id=\"bookDetailBtn\" src=\"resources/saveimg/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.imageurl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" booknum = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.booknum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" width=\"150\" height=\"150\">\n");
            out.write("</td>\n");
            out.write("<td>\n");
            out.write("<h2><a href=\"#\" id = \"bookDetailBtn\" booknum = \"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.booknum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></h2>\n");
            out.write("</td>\n");
            out.write("<td>\n");
            out.write("<h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.publisher}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\n");
            out.write("</td>\n");
            out.write("<td>\n");
            out.write("<h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\n");
            out.write("</td>\n");
            out.write("<td>\n");
            out.write("<h2>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${book.status }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h2>\n");
            out.write("</td>\n");
            out.write("</tr>\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
